version: "3.7"
services:
    app:
        build:
            args:
                user: opencfdi
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: opencfdi
        container_name: opencfdi-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./docker-compose/php/project.ini:/usr/local/etc/php/conf.d/project.ini
        networks:
            - opencfdi
        depends_on:
            - db
    db:
        image: mysql:8
        container_name: opencfdi-db
        restart: unless-stopped
        ports:
            - ${DOCKER_DB_PORT}:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql/init:/docker-entrypoint-initdb.d
            - ./docker-compose/mysql/persistent:/var/lib/mysql
        networks:
            - opencfdi
    nginx:
        image: nginx:stable-alpine
        container_name: opencfdi-nginx
        restart: unless-stopped
        ports:
            - ${DOCKER_APP_PORT}:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - opencfdi
        depends_on:
            - db
networks:
    opencfdi:
        driver: bridge
